### ISSUE TITLE
Should return to the main screen when the game play is over.

### ISSUE THREAD

**Issue by disjukr** [gorisanson/pikachu-volleyball#2]
It goes back to main screen 8.5 seconds after the game over in original client, but I don't know the exact constant.

**Comment by gorisanson** [comment]
The number of game end frame (which is set to `this.framTotal.gameEnd` of `PikachuVolleyball` object) was `211` before the commit 4434679e9e4dc4eba3f539508fb94a9a1a13e8ec. This value corresponds to 8.44 seconds (211 * 40ms) which is almost same as 8.5 seconds you said.

I found that the game end scene is enjoyable if it lasts long, so I set the number of frame to `Infinity`. I know it is a deviation from the original version. But I want to keep it so that others can enjoy the game end scene too. :)

Is it OK for you?

**Comment by disjukr** [comment]
Oh I didn't know it was the intended behavior. 😅 
It would be nice if the differences were stated in README.

By the way, there is a mail I sent to your gmail. Have you seen it?

**Comment by gorisanson** [comment]
Good. I'll close this issue after stating it in README.

Yeah. I'm writing a reply now:)

**Comment by gorisanson** [comment]
I decided to revert it to `211` as before (bf8a460087fabb3b34051df3fd11f1b21f8040c8), since I concluded that it is not appropriate to deviate from the original game intendedly just based on my preference. Thank you again!
